### ISSUE TITLE
Adjust Autocomplete to use react-autocomplete

### ISSUE THREAD

**Issue by martypowell** [baltimorecounty/react-trash-lookup#2]
See here for how autocomplete should work https://ant.design/components/auto-complete/

Steps to recreate

1. Type "1"
1. Push the arrow key down

Expected Behavior

After you push the down arrow "1745 T Street Southeast" should be highlighted and you should be able to select it with the enter key.

**Comment by martypowell** [comment]
We found this to be invalid based on the updated version, but would like to use https://github.com/reactjs/react-autocomplete in place of the existing logic.

Reasoning being that this will help simplify our logic, it's accessible and has been tested.

**Comment by sgrg1** [comment]
used auto-complete per your advice

**Comment by sgrg1** [comment]
used auto-complete per your advice
