### ISSUE TITLE
Combine Type and Image into One Column

### ISSUE THREAD

**Issue by martypowell** [baltimorecounty/react-trash-lookup#6]
The Type and Image columns should be combined into one column. The Icon will will be listed first and then the text that will describe the icon.

Example

{IconGoesHere} Trash

**Comment by martypowell** [comment]
As part of this issue, you might want to consolidate the icon components (Leaf, Trash, Recycle) you have into one component.

**Comment by sgrg1** [comment]
combined per your advice

**Comment by sgrg1** [comment]
Added icon component to consolidate the image
