### ISSUE TITLE
Add Entered Address to the Results and Hide the Search Input

### ISSUE THREAD

**Issue by martypowell** [baltimorecounty/react-trash-lookup#7]
The results section should reflect this mockup (content only, do not worry about the styling for now).

![image](https://user-images.githubusercontent.com/1933400/53820801-84317e80-3f3a-11e9-8b5d-9bed9757b136.png)

In the mockup there is no label for the icon, but this should be there.

**Comment by martypowell** [comment]
Download schedule can be excluded for the time being.

**Comment by martypowell** [comment]
Checkout this wireframe for the updates look and feel

![image](https://user-images.githubusercontent.com/1933400/53820801-84317e80-3f3a-11e9-8b5d-9bed9757b136.png)

**Comment by martypowell** [comment]
@sgrg1 it looks like you have the your schedule piece, just missing the link to try another search and hiding the search input.

**Comment by sgrg1** [comment]
added schedule linked for showing/hiding search input

**Comment by sgrg1** [comment]
added schedule linked for showing/hiding search input
